USE [master]
GO

/****** Object:  Database [HandsOnTwo]    Script Date: 11/23/2015 9:43:02 PM ******/
CREATE DATABASE [HandsOnTwo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HandsOnTwo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVERCSU\MSSQL\DATA\HandsOnTwo.mdf' , SIZE = 40960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 15360KB )
 LOG ON 
( NAME = N'HandsOnTwo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVERCSU\MSSQL\DATA\HandsOnTwo_log.ldf' , SIZE = 15360KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HandsOnTwo] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HandsOnTwo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HandsOnTwo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HandsOnTwo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HandsOnTwo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HandsOnTwo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HandsOnTwo] SET ARITHABORT OFF 
GO

ALTER DATABASE [HandsOnTwo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HandsOnTwo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HandsOnTwo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HandsOnTwo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HandsOnTwo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HandsOnTwo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HandsOnTwo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HandsOnTwo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HandsOnTwo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HandsOnTwo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HandsOnTwo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HandsOnTwo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HandsOnTwo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HandsOnTwo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HandsOnTwo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HandsOnTwo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HandsOnTwo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HandsOnTwo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HandsOnTwo] SET RECOVERY FULL 
GO

ALTER DATABASE [HandsOnTwo] SET  MULTI_USER 
GO

ALTER DATABASE [HandsOnTwo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HandsOnTwo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HandsOnTwo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HandsOnTwo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HandsOnTwo] SET  READ_WRITE 
GO


Alter Database HandsOnTwo Modify Name = HandsOnTwo_Delete; 
Go

Drop Database HandsOnTwo_Delete;
Go

