
--Select @@VERSION;
/*

Author: Sumita Rai
Purpose: iSell DLL generated from data model revised on 4/2/2016

Modification History:
	-- user	-- date  -- comment
	rais - 4/2/2016 - Version 1.0
	
*/

use iSell;

-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-04-02 09:47:01 MDT
--   site:      SQL Server 2012
--   type:      SQL Server 2012




CREATE
  TABLE Address_Book
  (
    Address_ID   NUMERIC (10) NOT NULL ,
    Vendor_Type  VARCHAR (1) NOT NULL ,
    Seq_ID       NUMERIC (7) NOT NULL ,
    Street       VARCHAR (40) ,
    City         VARCHAR (25) ,
    State_CD     VARCHAR (2) NOT NULL ,
    Zip          VARCHAR (10) ,
    Country_CD   VARCHAR (2) NOT NULL ,
    Address_Type VARCHAR (3)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Address_Book:
- It stores addresses for Project_Designer and Product_Supplier.
---- Address_Book.Address_ID references to Product_Designer.Designer_ID
---- Address_Book.Address_ID references to Product_Supplier.Supplier_ID
- Address_Type = D | S (Designer | Supplier)
'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Address_ID is Product_Designer.Designer_ID or Product_Supplier.Supplier_ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'Address_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Vendor_Type;
D = Product Designer
S = Product Supplier
' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'Vendor_Type'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Unique Sequence ID for Address_ID and Address Type' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'Seq_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Streeet Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'Street'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'City' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'City'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'ZIP' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'Zip'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Address_Type;
primary,secondary or ware house locations' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Address_Book' ,
'COLUMN' ,
'Address_Type'
GO
ALTER TABLE Address_Book ADD CONSTRAINT "Address_Book PK" PRIMARY KEY CLUSTERED
(Address_ID, Vendor_Type, Seq_ID, State_CD, Country_CD)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Admin_User
  (
    User_ID        NUMERIC (3) NOT NULL ,
    email_id       VARCHAR (50) ,
    Login_Password VARCHAR (20) ,
    Ins_Date       DATE ,
    Active_Ind     VARCHAR (1) NOT NULL ,
    Admin_Type_ID  NUMERIC (2)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin_User UID. Reference source to Product.Added_by_ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User' ,
'COLUMN' ,
'User_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'email_id-use as login id and business communication purpose' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User' ,
'COLUMN' ,
'email_id'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin user password' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User' ,
'COLUMN' ,
'Login_Password'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin user created date/time' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User' ,
'COLUMN' ,
'Ins_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Y|N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User' ,
'COLUMN' ,
'Active_Ind'
GO
ALTER TABLE Admin_User ADD CONSTRAINT "Admin_User PK" PRIMARY KEY CLUSTERED (
User_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Admin_User_Function_Ref
  (
    ID            NUMERIC (28) NOT NULL ,
    Function_ID   NUMERIC (28) NOT NULL ,
    Admin_Type_ID NUMERIC (2) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Admin_User_Function_Ref ADD CONSTRAINT "Admin_User_Function_Ref PK"
PRIMARY KEY CLUSTERED (Function_ID, Admin_Type_ID, ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Admin_User_Info
  (
    User_ID     NUMERIC (3) NOT NULL ,
    First_Name  VARCHAR (30) ,
    Middle_Name VARCHAR (1) ,
    Last_Name   VARCHAR (30) ,
    email_id    VARCHAR (50) ,
    Cell_Phone  VARCHAR (10)
  )
  ON "default"
GO
ALTER TABLE Admin_User_Info ADD CONSTRAINT "Admin_User_Info PK" PRIMARY KEY
CLUSTERED (User_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Admin_User_Log
  (
    Log_ID   NUMERIC (28) NOT NULL ,
    User_ID  NUMERIC (3) ,
    Log_Date DATE ,
    Action   VARCHAR (25)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Adming_User_Log UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User_Log' ,
'COLUMN' ,
'Log_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin User Account Update Date/Time' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User_Log' ,
'COLUMN' ,
'Log_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Adming User Action (e.g. Password Change, Adming Type Change, Profile Change etc)'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User_Log' ,
'COLUMN' ,
'Action'
GO
ALTER TABLE Admin_User_Log ADD CONSTRAINT "Admin_User_Log PK" PRIMARY KEY
CLUSTERED (Log_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Admin_User_Type
  (
    Admin_Type_ID  NUMERIC (2) NOT NULL ,
    Admin_Type     VARCHAR (25) ,
    Display_Ord_ID NUMERIC (28)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin_Type_ID - UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User_Type' ,
'COLUMN' ,
'Admin_Type_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin_Type;
SERVICE_PROVIDER
ADMIN_MANAGER
ADMIN_REPORT_USER' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Admin_User_Type' ,
'COLUMN' ,
'Admin_Type'
GO
ALTER TABLE Admin_User_Type ADD CONSTRAINT "Admin_User_Type PK" PRIMARY KEY
CLUSTERED (Admin_Type_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE App_Error_Log
  (
    LogID       NUMERIC (28) NOT NULL ,
    Ins_Date    DATE ,
    User_Name   VARCHAR (30) ,
    Module_Name VARCHAR (60) ,
    App_Msg     VARCHAR (4000) ,
    Error_Msg   VARCHAR (4000)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'App_Error_Log is to capture database error' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Error_Log'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'App_Error_Log UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Error_Log' ,
'COLUMN' ,
'LogID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Database user name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Error_Log' ,
'COLUMN' ,
'User_Name'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Package, Function, Procedure, Trigger etc Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Error_Log' ,
'COLUMN' ,
'Module_Name'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'User defined Application Error Message' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Error_Log' ,
'COLUMN' ,
'App_Msg'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Database Error' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Error_Log' ,
'COLUMN' ,
'Error_Msg'
GO
ALTER TABLE App_Error_Log ADD CONSTRAINT "App_Error_Log PK" PRIMARY KEY
CLUSTERED (LogID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE App_Menu
  (
    Menu_ID           NUMERIC (28) NOT NULL ,
    Display_Seq_ID    NUMERIC (28) ,
    Active_Ind        VARCHAR (1) ,
    Has_Child         VARCHAR (1) ,
    Parent_Text       VARCHAR (30) ,
    Enabled           VARCHAR (15) ,
    NavigateUrl       VARCHAR (1000) ,
    PopOutImageUrl    VARCHAR (255) ,
    Selectable        VARCHAR (15) ,
    SeparatorImageUrl VARCHAR (255) ,
    Target            VARCHAR (15) ,
    Text              VARCHAR (30) ,
    ToolTip           VARCHAR (1000) ,
    Value             VARCHAR (30) ,
    Ins_Date          DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Application Menu Store' ,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Menu'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'--Add this stmt to define the Ins_Date with GETDATE() default date
ALTER TABLE App_Menu ADD CONSTRAINT DF_App_Menu_Ins_Date DEFAULT GETDATE() FOR Ins_Date
GO'
,
'USER' ,
'iSell' ,
'TABLE' ,
'App_Menu' ,
'COLUMN' ,
'Ins_Date'
GO
ALTER TABLE App_Menu ADD CONSTRAINT "App_Menu PK" PRIMARY KEY CLUSTERED (
Menu_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Billing_Info
  (
    Order_ID       NUMERIC (10) NOT NULL ,
    email_id       VARCHAR (255) ,
    First_Name     VARCHAR (30) ,
    MIddle_Name    VARCHAR (1) ,
    Last_Name      VARCHAR (30) ,
    Street         VARCHAR (40) ,
    Address_Line_2 VARCHAR (40) ,
    City           VARCHAR (25) ,
    Zip            VARCHAR (10) ,
    State_CD       VARCHAR (2) ,
    Country_CD     VARCHAR (2) ,
    Ins_Date       DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Billing_Info captures customer billing information for the order
-If customer is logged in to the system, data is read from customer_info table
-or else allow to free form entry. In either case the data is editable.'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Billing_Info' ,
'COLUMN' ,
'Order_ID'
GO
ALTER TABLE Billing_Info ADD CONSTRAINT "Billing_Info PK" PRIMARY KEY CLUSTERED
(Order_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Business_Info
  (
    Address_ID     SMALLINT NOT NULL ,
    Name           VARCHAR (100) ,
    POBOX          INTEGER ,
    Street         VARCHAR (40) ,
    Address_Line_2 VARCHAR (40) ,
    City           VARCHAR (25) ,
    Zip            VARCHAR (10) ,
    State_CD       VARCHAR (2) ,
    Country_CD     VARCHAR (2) ,
    Phone          VARCHAR (15) ,
    email          VARCHAR (255) ,
    Website        VARCHAR (255) ,
    Address_Type   VARCHAR (1) ,
    Ins_Date       DATE
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Stores Business Information
- Mailing Information
- Billing Information
- Return Information'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Business_Info'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Business POBOX' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Business_Info' ,
'COLUMN' ,
'POBOX'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'1-888-777-1234' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Business_Info' ,
'COLUMN' ,
'Phone'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'M - Mailing Address
B - Business Address
S - Shipping Address' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Business_Info' ,
'COLUMN' ,
'Address_Type'
GO
ALTER TABLE Business_Info ADD CONSTRAINT "Business_Info PK" PRIMARY KEY
CLUSTERED (Address_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Country_CD
  (
    Country_CD     VARCHAR (2) NOT NULL ,
    Country_Name   VARCHAR (40) NOT NULL ,
    Display_IND    VARCHAR ,
    Display_Ord_ID NUMERIC (3)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'2 characters Country Code' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Country_CD' ,
'COLUMN' ,
'Country_CD'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Country Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Country_CD' ,
'COLUMN' ,
'Country_Name'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Yes (Y)/No (N)' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Country_CD' ,
'COLUMN' ,
'Display_IND'
GO
ALTER TABLE Country_CD ADD CONSTRAINT "Country_Code PK" PRIMARY KEY CLUSTERED (
Country_CD)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Customer_Authorization
  (
    email_id   VARCHAR (255) NOT NULL ,
    Password   VARCHAR (255) ,
    Active_IND VARCHAR (1) ,
    Ins_Date   DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Customer_Authorization keeps the Active|Inactive email id and login password'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Authorization'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'email_id of customer' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Authorization' ,
'COLUMN' ,
'email_id'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Customer Login Password' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Authorization' ,
'COLUMN' ,
'Password'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Y|N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Authorization' ,
'COLUMN' ,
'Active_IND'
GO
ALTER TABLE Customer_Authorization ADD CONSTRAINT "Customer_Authorization PK"
PRIMARY KEY CLUSTERED (email_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Customer_Feedback
  (
    Feedback_ID       NUMERIC (28) NOT NULL ,
    Feedback_Date     DATETIME ,
    Store_ID          NUMERIC (3) ,
    Fedback_Txt       VARCHAR (4000) ,
    Rating            NUMERIC (3) ,
    Customer_IP       VARCHAR (45) ,
    Customer_Email_ID VARCHAR (255) ,
    Publish_Ind       VARCHAR (1) ,
    Publish_Date      DATETIME ,
    User_ID           NUMERIC (3)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'1 - 5
1- Poor - 1 star
5 - Excellent - 5 star' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Feedback' ,
'COLUMN' ,
'Rating'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Default to N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Feedback' ,
'COLUMN' ,
'Publish_Ind'
GO
ALTER TABLE Customer_Feedback ADD CONSTRAINT Customer_Feedback_PK PRIMARY KEY
CLUSTERED (Feedback_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Customer_Info
  (
    email_id       VARCHAR (255) NOT NULL ,
    First_Name     VARCHAR (30) ,
    Middle_Name    CHAR (1) ,
    Last_Name      VARCHAR (30) ,
    Street         VARCHAR (40) ,
    Address_Line_2 VARCHAR (40) ,
    City           VARCHAR (25) ,
    Zip            VARCHAR (10) ,
    State_CD       VARCHAR (2) ,
    Country_CD     VARCHAR (2) ,
    Subscribe_Ind  VARCHAR (1) ,
    Ins_Date       DATE
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Collects [Email Sign-up] user information for the following purpose;
1- Sign up for emails and be the first to know about exclusive sales, special offers and more.
2- If user "Create Account" with the email id, user purchase is tracked for additional services'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Info'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Customer Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Info' ,
'COLUMN' ,
'First_Name'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Apt. or Suite #' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Info' ,
'COLUMN' ,
'Address_Line_2'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Whether customer wills to subscribe mails.
Y|N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Info' ,
'COLUMN' ,
'Subscribe_Ind'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Customer registration date and time' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Info' ,
'COLUMN' ,
'Ins_Date'
GO
ALTER TABLE Customer_Info ADD CONSTRAINT "Customer_Info PK" PRIMARY KEY
CLUSTERED (email_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Customer_Info_Log
  (
    Customer_Info_Log_ID NUMERIC (7) NOT NULL ,
    email_id             VARCHAR (255) NOT NULL ,
    Log_Date             DATE ,
    Action               VARCHAR (255) ,
    Customer_IP_Address  VARCHAR (45)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Customer_Info_Log captures anytime Customer takes an action to his account. (e.g. Password Change, Address Change etc)
Note - Lock the account (Customer_Authorization.Active_IND=N) upon 3 unsuccessful login attampt.'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Customer_Info_Log'
GO
ALTER TABLE Customer_Info_Log ADD CONSTRAINT "Customer_Info_Log PK" PRIMARY KEY
CLUSTERED (Customer_Info_Log_ID, email_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Demo_Access_Request
  (
    DAR_ID             NUMERIC (7) NOT NULL ,
    Requestor_Email_ID VARCHAR (255) ,
    Demo_by_SP         VARCHAR (1) ,
    Requestor_Name     VARCHAR (30) ,
    Requestor_Phone    VARCHAR (15) ,
    Note_to_SP         VARCHAR (1000) ,
    Demo_CD            VARCHAR (15) ,
    Demo_Active_Date   DATETIME ,
    Demo_CD_Active_Ind VARCHAR (1)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Demo Acess Request Entry Table. This is the seed table for Demo Access Request. It stores Demo Request ID, Reqestor Email, Demo_CD etc'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'DAR - Demo Access Request ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request' ,
'COLUMN' ,
'DAR_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Demo was requested to present by Service Provider = Y | N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request' ,
'COLUMN' ,
'Demo_by_SP'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Note to Service Provider about Demo when requested to be presented by the SP'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request' ,
'COLUMN' ,
'Note_to_SP'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Autogenerated CD {2 char from email + ddmmyy}' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request' ,
'COLUMN' ,
'Demo_CD'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Y | N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request' ,
'COLUMN' ,
'Demo_CD_Active_Ind'
GO
ALTER TABLE Demo_Access_Request ADD CONSTRAINT "Demo_Access_Request PK" PRIMARY
KEY CLUSTERED (DAR_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Demo_Access_Request_Auth
  (
    IP            VARCHAR (45) ,
    Demo_CD       VARCHAR (15) ,
    Auth_Date     DATETIME ,
    Auth_Pass_Ind VARCHAR (1)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'One time Authentication to Demo' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request_Auth'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'One time Authentication Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request_Auth' ,
'COLUMN' ,
'Auth_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Authentication Pass Indicator= Y|N' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Demo_Access_Request_Auth' ,
'COLUMN' ,
'Auth_Pass_Ind'
GO


CREATE
  TABLE Functions
  (
    Function_ID  NUMERIC (28) NOT NULL ,
    Function_Txt VARCHAR (30) NOT NULL ,
    Module_Txt   VARCHAR (30)
  )
  ON "default"
GO
ALTER TABLE Functions ADD CONSTRAINT "Function PK" PRIMARY KEY CLUSTERED (
Function_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE "JUST TO MAKE THE VERTICAL SCROLL BAR WORK"
  -- No columns
  ON "default"
GO


CREATE
  TABLE Key_Value_Store_Log
  (
    ID       NUMERIC (7) NOT NULL ,
    Key_Txt  VARCHAR (30) ,
    Value    VARCHAR (255) ,
    User_IP  VARCHAR (45) ,
    Ins_Date DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Key_Value_Store - is to capture the key and corresponding values 
e.g. key = CLIENT_LOGIN-PASSWORD_FORGOT / value = PASSWORD FORGOT REQUEST
key convention = nature of action + "-" + action
value = nature of value'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Key_Value_Store_Log'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Primary Key' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Key_Value_Store_Log' ,
'COLUMN' ,
'ID'
GO
ALTER TABLE Key_Value_Store_Log ADD CONSTRAINT "Key_Value_Store PK" PRIMARY KEY
CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Kids_Product_Code
  (
    Kids_Code   NUMERIC (2) NOT NULL ,
    Code_Txt    VARCHAR (30) NOT NULL ,
    Description VARCHAR (4000)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Kids_Code UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Kids_Product_Code' ,
'COLUMN' ,
'Kids_Code'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'I = Infant (0-1 yrs)
T = Toddler (1-5 yrs)
Y = Youth (5-9 yrs)
J = Junior (9-13 yrs)'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Kids_Product_Code' ,
'COLUMN' ,
'Code_Txt'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Kids_Code Description' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Kids_Product_Code' ,
'COLUMN' ,
'Description'
GO
ALTER TABLE Kids_Product_Code ADD CONSTRAINT "Kids_Product_Code PK" PRIMARY KEY
CLUSTERED (Kids_Code)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Master_Product
  (
    Master_Product_ID NUMERIC (28) NOT NULL ,
    Designer_ID       NUMERIC (28) NOT NULL ,
    Supplier_ID       NUMERIC (28) NOT NULL
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Master Product UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Master_Product' ,
'COLUMN' ,
'Master_Product_ID'
GO
ALTER TABLE Master_Product ADD CONSTRAINT "Master_Product PK" PRIMARY KEY
CLUSTERED (Master_Product_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Order_Detail
  (
    Order_ID       NUMERIC (10) NOT NULL ,
    Product_ID     NUMERIC (28) ,
    Product_Seq_ID NUMERIC (28) ,
    Quantity       NUMERIC (28) ,
    Unit_Price     NUMERIC (28) NOT NULL
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product_Detail.Product_Seq_ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Detail' ,
'COLUMN' ,
'Product_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product_Detail.Product_Seq_ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Detail' ,
'COLUMN' ,
'Product_Seq_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Quantity' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Detail' ,
'COLUMN' ,
'Quantity'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Unit Price' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Detail' ,
'COLUMN' ,
'Unit_Price'
GO
ALTER TABLE Order_Detail ADD CONSTRAINT "Order_Detail PK" PRIMARY KEY CLUSTERED
(Order_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Order_Detail_Temp
  (
    Session_ID VARCHAR (128) NOT NULL ,
    Seq_ID     NUMERIC (7) NOT NULL ,
    email_id   VARCHAR (255) ,
    Order_Date DATETIME ,
    Product_ID NUMERIC (28) ,
    Quantity   NUMERIC (10) ,
    Unit_Price NUMERIC (9,2) ,
    Status_CD  VARCHAR (15)
  )
  ON "default"
GO
ALTER TABLE Order_Detail_Temp ADD CONSTRAINT "Order_Detail_Temp PK" PRIMARY KEY
CLUSTERED (Session_ID, Seq_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Order_Header
  (
    Order_ID                   NUMERIC (10) NOT NULL ,
    Submitted_Date             DATE NOT NULL ,
    Requested_Date             DATE ,
    Description                VARCHAR (4000) ,
    Customer_IP_Address        VARCHAR (45) ,
    Order_Entry_Completed_Date DATETIME ,
    email_id                   VARCHAR (50)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Order_Header UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Header' ,
'COLUMN' ,
'Order_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Order Submitted Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Header' ,
'COLUMN' ,
'Submitted_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Order Delivery Requested by Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Header' ,
'COLUMN' ,
'Requested_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Client Description about the Order' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Header' ,
'COLUMN' ,
'Description'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Supports IPv4 and IPv6' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Header' ,
'COLUMN' ,
'Customer_IP_Address'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Order Entry Completed Date captures when the order is successfully placed by user.'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Header' ,
'COLUMN' ,
'Order_Entry_Completed_Date'
GO
ALTER TABLE Order_Header ADD CONSTRAINT "Order_Header PK" PRIMARY KEY CLUSTERED
(Order_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Order_Payment_Shipping_Method
  (
    Order_ID             NUMERIC (10) NOT NULL ,
    Payment_Type         VARCHAR (15) ,
    Payment_Process_Date DATETIME ,
    Shipping_Rate_ID     NUMERIC (10) NOT NULL ,
    Shipping_Tracking_NO VARCHAR (25) ,
    Transaction_ID       VARCHAR (30) ,
    Total_Amount         NUMERIC (9,2)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'C = Credit Card
P = PayPal' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Payment_Shipping_Method' ,
'COLUMN' ,
'Payment_Type'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'DateTime when customer click Buy Now button' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Payment_Shipping_Method' ,
'COLUMN' ,
'Payment_Process_Date'
GO
ALTER TABLE Order_Payment_Shipping_Method ADD CONSTRAINT "Order_Shippingv2 PK"
PRIMARY KEY CLUSTERED (Order_ID, Shipping_Rate_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Order_Receipt
  (
    Order_ID             NUMERIC (28) NOT NULL ,
    Receipt_Name         VARCHAR (255) ,
    Create_DateTime      DATETIME ,
    Last_Access_DateTime DATETIME
  )
  ON "default"
GO
ALTER TABLE Order_Receipt ADD CONSTRAINT "Order_Receipt PK" PRIMARY KEY
CLUSTERED (Order_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Order_Shipping
  (
    Order_ID       NUMERIC (10) NOT NULL ,
    First_Name     VARCHAR (30) ,
    Last_Name      VARCHAR (30) ,
    Street         VARCHAR (40) ,
    Address_Line_2 VARCHAR (20) ,
    City           VARCHAR (25) ,
    State_CD       VARCHAR (2) NOT NULL ,
    Zip            VARCHAR (10) ,
    Country_CD     VARCHAR (2) ,
    Order_Status   VARCHAR (1)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Apt or Suite #' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Shipping' ,
'COLUMN' ,
'Address_Line_2'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Order Status-
I = In Progress
M = Mailed
D = Delivered' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Order_Shipping' ,
'COLUMN' ,
'Order_Status'
GO
ALTER TABLE Order_Shipping ADD CONSTRAINT "Order_Shipping PK" PRIMARY KEY
CLUSTERED (Order_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE PayPal_Setting
  (
    ID                NUMERIC (3) NOT NULL ,
    Key_ID            VARCHAR (30) ,
    Value             VARCHAR (255) ,
    Key_Description   VARCHAR (1000) ,
    Last_Upd_DateTime DATETIME ,
    Last_Upd_by_ID    NUMERIC (3)
  )
  ON "default"
GO
ALTER TABLE PayPal_Setting ADD CONSTRAINT "PayPal_Setting PK" PRIMARY KEY
CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO
ALTER TABLE PayPal_Setting ADD CONSTRAINT PayPal_Setting_UN01 UNIQUE
NONCLUSTERED (Key_ID)
ON "default"
GO

CREATE
  TABLE Product
  (
    Product_ID        NUMERIC (10) NOT NULL ,
    SKU               VARCHAR (30) NOT NULL ,
    Name              VARCHAR (255) ,
    Description       VARCHAR (4000) ,
    Quantity          NUMERIC (18) NOT NULL ,
    Master_Product_ID NUMERIC (10) NOT NULL ,
    Product_Type      CHAR (2) ,
    Sales_Method      VARCHAR (1) NOT NULL ,
    Added_by_ID       NUMERIC (18) ,
    Added_DateTime    DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product Unique Identifier' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product' ,
'COLUMN' ,
'Product_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product level SKU
AAAA+PRODUCT_ID
e.g.SHRT123' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product' ,
'COLUMN' ,
'SKU'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product Long Description' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product' ,
'COLUMN' ,
'Description'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Overall quantity - includes all sizes, colors and genders' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product' ,
'COLUMN' ,
'Quantity'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product_Type
AP - Apparel
PP - Paper Product
MU - Music
JW - Jewelry
ST - Statue
OT - Other'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Product' ,
'COLUMN' ,
'Product_Type'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Inventory added Date Time' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product' ,
'COLUMN' ,
'Added_DateTime'
GO
ALTER TABLE Product ADD CONSTRAINT "Product PK" PRIMARY KEY CLUSTERED (
Product_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Color
  (
    Color          VARCHAR (3) NOT NULL ,
    Color_Txt      VARCHAR (15) ,
    Display_Seq_ID NUMERIC (3)
  )
  ON "default"
GO
ALTER TABLE Product_Color ADD CONSTRAINT "Product_Color PK" PRIMARY KEY
CLUSTERED (Color)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Designer
  (
    Designer_ID NUMERIC (28) NOT NULL ,
    Name        VARCHAR (100) NOT NULL ,
    URL         VARCHAR (255) ,
    Description VARCHAR (4000) ,
    Ins_Date    DATE
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Designer Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Designer' ,
'COLUMN' ,
'Name'
GO
ALTER TABLE Product_Designer ADD CONSTRAINT "Product_Designer PK" PRIMARY KEY
CLUSTERED (Designer_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Detail
  (
    Product_ID     NUMERIC (10) NOT NULL ,
    Product_Seq_ID NUMERIC (28) NOT NULL ,
    SKU            VARCHAR (30) ,
    Size           VARCHAR (3) ,
    Gender         VARCHAR (1) ,
    Kids_Code      NUMERIC (2) ,
    Color          VARCHAR (3) ,
    Season         VARCHAR (1) ,
    Weight         VARCHAR (15) ,
    Quantity       NUMERIC (28) ,
    Specification  VARCHAR (4000) ,
    Category1      VARCHAR (64)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product variant specific SKU
PRODUCT.SKU+SIZE+PRODUCT_SEQ_ID+COLOR
e.g.SHRT123XL5RED'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'SKU'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Size - S|M|L|XL|XXL' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'Size'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Gender = M|F|K {Male|Female|Kids}' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'Gender'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'RD = Red
GR = Green
BU = Blue
WH = White
YW = Yellow
' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'Color'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Sessions
S=Summer
W=Winter
A=All Session' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'Season'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Break out quantity by Size, Gender, Color and Season' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'Quantity'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product Category' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Detail' ,
'COLUMN' ,
'Category1'
GO
ALTER TABLE Product_Detail ADD CONSTRAINT "Product_Detail PK" PRIMARY KEY
CLUSTERED (Product_ID, Product_Seq_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO
ALTER TABLE Product_Detail ADD CONSTRAINT SKU_Unique UNIQUE NONCLUSTERED (SKU)
ON "default"
GO

CREATE
  TABLE Product_Picture
  (
    Product_ID        NUMERIC (10) NOT NULL ,
    Picture_Seq_ID    NUMERIC (28) NOT NULL ,
    Product_Seq_ID    NUMERIC (28) ,
    Picture_Path      VARCHAR (100) ,
    Picture_Name      VARCHAR (25) ,
    Picture_File_Type VARCHAR (4) ,
    Active_Ind        VARCHAR (1) ,
    Display_Ord_ID    NUMERIC (28)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Picture Sequence ID to the Product ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Picture' ,
'COLUMN' ,
'Picture_Seq_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product_Seq_ID maps to Product Variant specific picture. If the field is blank, picture ties to Product_ID'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Picture' ,
'COLUMN' ,
'Product_Seq_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Picture Library Path' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Picture' ,
'COLUMN' ,
'Picture_Path'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Picture File Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Picture' ,
'COLUMN' ,
'Picture_Name'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Picture Format Type. e.g. jpg,bmp,jpeg etc' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Picture' ,
'COLUMN' ,
'Picture_File_Type'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Y=Active
N=Deactive' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Picture' ,
'COLUMN' ,
'Active_Ind'
GO
ALTER TABLE Product_Picture ADD CONSTRAINT "Product_Picture PK" PRIMARY KEY
CLUSTERED (Picture_Seq_ID, Product_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Price
  (
    Product_ID                 NUMERIC (10) NOT NULL ,
    Price_Seq_ID               NUMERIC (28) NOT NULL ,
    Product_Seq_ID             NUMERIC (28) ,
    Price_Effective_Start_Date DATE NOT NULL ,
    Price_Effective_End_Date   DATE ,
    Price                      NUMERIC (28) NOT NULL ,
    Added_Updated_by_ID        NUMERIC (28) NOT NULL ,
    Active_Price_Ind           VARCHAR (1)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Sequence ID per Product ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Price' ,
'COLUMN' ,
'Price_Seq_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product_Seq_ID maps to Product Variant specific price. If the field is blank, price ties to Product_ID'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Price' ,
'COLUMN' ,
'Product_Seq_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Price Effective Start Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Price' ,
'COLUMN' ,
'Price_Effective_Start_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Price Effective End Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Price' ,
'COLUMN' ,
'Price_Effective_End_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product Price in USD' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Price' ,
'COLUMN' ,
'Price'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'User ID who has Added or Updated the Price line' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Price' ,
'COLUMN' ,
'Added_Updated_by_ID'
GO
ALTER TABLE Product_Price ADD CONSTRAINT "Product_Price PK" PRIMARY KEY
CLUSTERED (Price_Seq_ID, Product_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Size
  (
    Size           VARCHAR (3) NOT NULL ,
    Size_Txt       VARCHAR (15) NOT NULL ,
    Display_Seq_ID NUMERIC (3)
  )
  ON "default"
GO
ALTER TABLE Product_Size ADD CONSTRAINT "Product_Size PK" PRIMARY KEY CLUSTERED
(Size)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Supplier
  (
    Supplier_ID NUMERIC (28) NOT NULL ,
    Name        VARCHAR (100) NOT NULL ,
    URL         VARCHAR (255) ,
    Description VARCHAR (4000) ,
    Ins_Date    DATE
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Production Supplier UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Supplier' ,
'COLUMN' ,
'Supplier_ID'
GO
ALTER TABLE Product_Supplier ADD CONSTRAINT "Product_Supplier PK" PRIMARY KEY
CLUSTERED (Supplier_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Type
  (
    Product_Type     VARCHAR (2) NOT NULL ,
    Product_Type_Txt VARCHAR (30) ,
    Display_Seq_ID   NUMERIC (28)
  )
  ON "default"
GO
ALTER TABLE Product_Type ADD CONSTRAINT "Product_Type PK" PRIMARY KEY CLUSTERED
(Product_Type)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Product_Type_to_Page
  (
    ID           NUMERIC (28) NOT NULL ,
    Product_Type VARCHAR (2) ,
    Page_Name    VARCHAR (30) ,
    Page_Type    VARCHAR (15) ,
    Ins_Date     DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product_Type_to_Page stores the product type and corresponding Page and Page Type'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Type_to_Page'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Prmary Key' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Type_to_Page' ,
'COLUMN' ,
'ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Reference to Product_Type.Product_Type' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Type_to_Page' ,
'COLUMN' ,
'Product_Type'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Pagename e.g. item.aspx or item_detail.aspx' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Type_to_Page' ,
'COLUMN' ,
'Page_Name'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Page_Type e.g
-DISPLAY_ITEM
-DISPLAY_DETAIL' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Product_Type_to_Page' ,
'COLUMN' ,
'Page_Type'
GO
ALTER TABLE Product_Type_to_Page ADD CONSTRAINT "Product_Type_to_Page PK"
PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Promo_CD
  (
    Promo_ID               NUMERIC (28) NOT NULL ,
    Promo_CD               VARCHAR (20) NOT NULL ,
    Promo_Start_Date       DATE NOT NULL ,
    Promo_End_Date         DATE NOT NULL ,
    Promo_Spec             VARCHAR (100) ,
    Promo_Value            NUMERIC (3) ,
    Added_Updated_by_ID    NUMERIC (28) ,
    Last_Modified_DateTime DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product Promotional Code for List of Product_ID or List of Master_Product_ID effective during the Promo Date.
- If Master_Product_ID exist, apply to all products in Product table
- If Master_Product_ID does not exist, apply only to the Product_ID'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Promo Code UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Promo_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Promotional Code' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Promo_CD'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Promotional Start Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Promo_Start_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Promotional End Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Promo_End_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'PERCENT_DISCOUNT
STORE_CREDIT
BUY_1_GET_2_HALF
FREE_SHIPPING
TWO_FOR_ONE
' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Promo_Spec'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Pomotions value in percent
' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Promo_Value'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Admin user ID - who has modified the Promo CD' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Added_Updated_by_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'PromoCD last modified DateTime' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Promo_CD' ,
'COLUMN' ,
'Last_Modified_DateTime'
GO
ALTER TABLE Promo_CD ADD CONSTRAINT "Promo_Code PK" PRIMARY KEY CLUSTERED (
Promo_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Promo_CD_Detail
  (
    Promo_ID   NUMERIC (28) NOT NULL ,
    Product_ID NUMERIC (10) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Promo_CD_Detail ADD CONSTRAINT "Promo_CD_Detail PK" PRIMARY KEY
CLUSTERED (Promo_ID, Product_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Recently_Viewed_Product
  (
    Customer_IP_Address VARCHAR (45) ,
    Viewed_DateTime     DATETIME ,
    Product_ID          NUMERIC (10) ,
    Email_ID            VARCHAR (255)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Product viewed DateTime' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Recently_Viewed_Product' ,
'COLUMN' ,
'Viewed_DateTime'
GO


CREATE
  TABLE Shipping_Rate
  (
    Shipping_Rate_ID       NUMERIC (28) NOT NULL ,
    Shipping_Type          VARCHAR (255) ,
    Purchase_From_Amt      NUMERIC (9,2) ,
    Purchase_To_Amt        NUMERIC (9,2) ,
    Shipping_Rate          NUMERIC (9,2) ,
    Estm_Delivery_Min_Days NUMERIC (3) ,
    Estm_Delivery_Max_Days NUMERIC (3) ,
    Shipping_Free_St_Date  DATE ,
    Shipping_Free_End_Date DATE ,
    Ins_Date               DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Purchase Range - Min Price' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Shipping_Rate' ,
'COLUMN' ,
'Purchase_From_Amt'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Purchase Range - Max Price' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Shipping_Rate' ,
'COLUMN' ,
'Purchase_To_Amt'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Delivery Date Range - Estimated Delivery Earliest Date - Now + business days'
,
'USER' ,
'iSell' ,
'TABLE' ,
'Shipping_Rate' ,
'COLUMN' ,
'Estm_Delivery_Min_Days'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Delivery Date Range - Estimated Delivery Latest Date - Now + business days' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Shipping_Rate' ,
'COLUMN' ,
'Estm_Delivery_Max_Days'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Shipping Free during Shipping_Free_St_Date to Shipping_Free_End_Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Shipping_Rate' ,
'COLUMN' ,
'Shipping_Free_St_Date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Shipping Free during Shipping_Free_St_Date to Shipping_Free_End_Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'Shipping_Rate' ,
'COLUMN' ,
'Shipping_Free_End_Date'
GO
ALTER TABLE Shipping_Rate ADD CONSTRAINT "Shipping_Rate PK" PRIMARY KEY
CLUSTERED (Shipping_Rate_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Social_Media_Link
  (
    Social_Media_ID    SMALLINT NOT NULL ,
    Name               VARCHAR (100) ,
    Icon_Filename      VARCHAR (25) ,
    URL                VARCHAR (255) ,
    Display_Ord_Seq_ID NUMERIC (28) ,
    Active_Ind         VARCHAR (1) ,
    Ins_Date           DATETIME
  )
  ON "default"
GO
ALTER TABLE Social_Media_Link ADD CONSTRAINT "Social_Media_Link PK" PRIMARY KEY
CLUSTERED (Social_Media_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE State_CD
  (
    State_CD    VARCHAR (2) NOT NULL ,
    State_Name  VARCHAR (25) NOT NULL ,
    Display_Ind VARCHAR (1)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'2 characters US State Code' ,
'USER' ,
'iSell' ,
'TABLE' ,
'State_CD' ,
'COLUMN' ,
'State_CD'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'US State Name' ,
'USER' ,
'iSell' ,
'TABLE' ,
'State_CD' ,
'COLUMN' ,
'State_Name'
GO
ALTER TABLE State_CD ADD CONSTRAINT "State_CD PK" PRIMARY KEY CLUSTERED (
State_CD)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE User_Inquiry
  (
    Inquiry_ID              NUMERIC (10) NOT NULL ,
    Product_ID              NUMERIC (10) ,
    URL                     VARCHAR (255) ,
    User_Name               VARCHAR (30) ,
    email_id                VARCHAR (255) ,
    Inquiry_Txt             VARCHAR (1000) ,
    Ins_Date                DATETIME ,
    Action_Ind              VARCHAR (1) ,
    Action_Taken_Date       DATETIME ,
    Action_Taken_by_User_ID NUMERIC (10)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'N = New
P = Processed
I = Ignored' ,
'USER' ,
'iSell' ,
'TABLE' ,
'User_Inquiry' ,
'COLUMN' ,
'Action_Ind'
GO
ALTER TABLE User_Inquiry ADD CONSTRAINT "user_question PK" PRIMARY KEY
CLUSTERED (Inquiry_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE User_Review
  (
    Review_ID            NUMERIC (7) NOT NULL ,
    Reviewer_Name        VARCHAR (30) ,
    Product_ID           NUMERIC (10) ,
    URL                  VARCHAR (255) ,
    Rating_Scale         NUMERIC (1) ,
    Review_Txt           VARCHAR (1000) ,
    Ins_Date             DATETIME ,
    Approval_to_Post_Ind VARCHAR (1) ,
    Last_Upd_Date        DATETIME ,
    Last_Upd_by_User_ID  NUMERIC (10)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'1  - 5 (Poor-Great)' ,
'USER' ,
'iSell' ,
'TABLE' ,
'User_Review' ,
'COLUMN' ,
'Rating_Scale'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'N=No -Default, Y=Yes' ,
'USER' ,
'iSell' ,
'TABLE' ,
'User_Review' ,
'COLUMN' ,
'Approval_to_Post_Ind'
GO
ALTER TABLE User_Review ADD CONSTRAINT "User_Review PK" PRIMARY KEY CLUSTERED (
Review_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Visitor_Log
  (
    Customer_IP_Address VARCHAR (45) ,
    Visit_DateTime      DATETIME ,
    Initial_URL         VARCHAR (255)
  )
  ON "default"
GO


CREATE
  TABLE iAddress
  (
    Contact_ID   NUMERIC (28) NOT NULL ,
    Contact_Data VARCHAR (100) ,
    Contact_Type VARCHAR (2)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Company Mailing Address' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iAddress'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Mailing Address UID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iAddress' ,
'COLUMN' ,
'Contact_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Contact_Data - mailing addres, email id, phone No' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iAddress' ,
'COLUMN' ,
'Contact_Data'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Contact_Type - M|E|P' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iAddress' ,
'COLUMN' ,
'Contact_Type'
GO
ALTER TABLE iAddress ADD CONSTRAINT "Mailing_Address PK" PRIMARY KEY CLUSTERED
(Contact_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE iBook
  (
    email_id    VARCHAR (255) NOT NULL ,
    seq_id      NUMERIC (28) ,
    Contact_ID  VARCHAR (255) NOT NULL ,
    Description VARCHAR (4000) ,
    Share_to_ID VARCHAR (4000)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'iBook 
- keeps URLs, emails, phones and faxes of business associates
- it allows to share the contacts among other email ids
'
,
'USER' ,
'iSell' ,
'TABLE' ,
'iBook'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'user email_id' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iBook' ,
'COLUMN' ,
'email_id'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Sequene ID' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iBook' ,
'COLUMN' ,
'seq_id'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'URL, email, phone, fax' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iBook' ,
'COLUMN' ,
'Contact_ID'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'list of emails that can access to iBook' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iBook' ,
'COLUMN' ,
'Share_to_ID'
GO
ALTER TABLE iBook ADD CONSTRAINT "iBook PK" PRIMARY KEY CLUSTERED (email_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE iReminder
  (
    email_id    VARCHAR (255) NOT NULL ,
    seq_id      NUMERIC (28) NOT NULL ,
    SCHEDULE    VARCHAR (20) ,
    Description VARCHAR (4000) ,
    Recipient   VARCHAR (4000) ,
    ins_date    DATE ,
    upd_date    DATE
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'iReminder - emails or calls the saved reminder' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iReminder'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'minute (0-59),
hour (0-23),
day of the month (1-31),
month of the year (1-12),
day of the week (0-6 with 0=Sunday).'
,
'USER' ,
'iSell' ,
'TABLE' ,
'iReminder' ,
'COLUMN' ,
'Schedule'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'list of emails or phone number to receive the reminder' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iReminder' ,
'COLUMN' ,
'Recipient'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Reminder Insert Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iReminder' ,
'COLUMN' ,
'ins_date'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Last Update Date' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iReminder' ,
'COLUMN' ,
'upd_date'
GO
ALTER TABLE iReminder ADD CONSTRAINT "iReminder PK" PRIMARY KEY CLUSTERED (
email_id, seq_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE iSearch_Dictionary
  (
    ID          NUMERIC (7) NOT NULL ,
    Product_ID  NUMERIC (10) ,
    Keyword     VARCHAR (255) ,
    Search_Rank NUMERIC (3) ,
    Ins_Date    DATETIME
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'iSearch_Dictionary store search keywork with search_rank for a product' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iSearch_Dictionary'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'A value or comma seperated values' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iSearch_Dictionary' ,
'COLUMN' ,
'Keyword'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Search Rank 
1 - highest
10 -lowest' ,
'USER' ,
'iSell' ,
'TABLE' ,
'iSearch_Dictionary' ,
'COLUMN' ,
'Search_Rank'
GO
ALTER TABLE iSearch_Dictionary ADD CONSTRAINT "iSearch_Dictionary PK" PRIMARY
KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE iSetting
  (
    ID                  NUMERIC (28) NOT NULL ,
    setting             VARCHAR (1000) ,
    setting_type        VARCHAR (1000) ,
    value               VARCHAR (1000) ,
    extended_value      VARCHAR (255) ,
    last_setup_datetime DATETIME ,
    User_ID             NUMERIC (3) NOT NULL ,
    description         VARCHAR (4000)
  )
  ON "default"
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Extended Value such as discount % for sales item i.e. setting = PRODUCTS_IN_THE_SALESPAGE'
,
'USER' ,
'iSell' ,
'TABLE' ,
'iSetting' ,
'COLUMN' ,
'extended_value'
GO
ALTER TABLE iSetting ADD CONSTRAINT "iSetting PK" PRIMARY KEY CLUSTERED (ID,
User_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

ALTER TABLE Admin_User_Info
ADD CONSTRAINT "Admin_User-Admin_User_Info" FOREIGN KEY
(
User_ID
)
REFERENCES Admin_User
(
User_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Admin_User_Log
ADD CONSTRAINT "Admin_User-Admin_User_Log" FOREIGN KEY
(
User_ID
)
REFERENCES Admin_User
(
User_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Customer_Feedback
ADD CONSTRAINT "Admin_User-To-Customer_Feedback" FOREIGN KEY
(
User_ID
)
REFERENCES Admin_User
(
User_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Admin_User
ADD CONSTRAINT "Admin_User_Type-Admin_User" FOREIGN KEY
(
Admin_Type_ID
)
REFERENCES Admin_User_Type
(
Admin_Type_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Admin_User_Function_Ref
ADD CONSTRAINT "Admin_User_Type-Admin_User_Function_Ref" FOREIGN KEY
(
Admin_Type_ID
)
REFERENCES Admin_User_Type
(
Admin_Type_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Customer_Info
ADD CONSTRAINT "Country_CD-Customer_Info" FOREIGN KEY
(
Country_CD
)
REFERENCES Country_CD
(
Country_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Order_Shipping
ADD CONSTRAINT "Country_CD-Order_Shipping" FOREIGN KEY
(
Country_CD
)
REFERENCES Country_CD
(
Country_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Billing_Info
ADD CONSTRAINT "Country_CD-To-Billing_Info" FOREIGN KEY
(
Country_CD
)
REFERENCES Country_CD
(
Country_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Address_Book
ADD CONSTRAINT "Country_Code-Address_Book" FOREIGN KEY
(
Country_CD
)
REFERENCES Country_CD
(
Country_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Customer_Info_Log
ADD CONSTRAINT "Customer_Info-Cust_Info_Log" FOREIGN KEY
(
email_id
)
REFERENCES Customer_Authorization
(
email_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Admin_User_Function_Ref
ADD CONSTRAINT "Functions-Admin_User_Function_Rref" FOREIGN KEY
(
Function_ID
)
REFERENCES Functions
(
Function_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Product_Detail
ADD CONSTRAINT "Kids_Prod_CD-Prod_Detail" FOREIGN KEY
(
Kids_Code
)
REFERENCES Kids_Product_Code
(
Kids_Code
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Product
ADD CONSTRAINT "Master_Product-Product" FOREIGN KEY
(
Master_Product_ID
)
REFERENCES Master_Product
(
Master_Product_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Order_Detail
ADD CONSTRAINT "Order_Header-Order_Detail" FOREIGN KEY
(
Order_ID
)
REFERENCES Order_Header
(
Order_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Order_Shipping
ADD CONSTRAINT "Order_Header-Order_Shipping" FOREIGN KEY
(
Order_ID
)
REFERENCES Order_Header
(
Order_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Order_Payment_Shipping_Method
ADD CONSTRAINT "Order_Header-Order_Shipping_Method" FOREIGN KEY
(
Order_ID
)
REFERENCES Order_Header
(
Order_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Billing_Info
ADD CONSTRAINT "Order_Header-To-Billing_Info" FOREIGN KEY
(
Order_ID
)
REFERENCES Order_Header
(
Order_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Master_Product
ADD CONSTRAINT "Prod_Designer-Master_Prod" FOREIGN KEY
(
Designer_ID
)
REFERENCES Product_Designer
(
Designer_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Master_Product
ADD CONSTRAINT "Prod_Supplier-Master_Prod" FOREIGN KEY
(
Supplier_ID
)
REFERENCES Product_Supplier
(
Supplier_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Product_Picture
ADD CONSTRAINT "Product-Product_Picture" FOREIGN KEY
(
Product_ID
)
REFERENCES Product
(
Product_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Product_Price
ADD CONSTRAINT "Product-Product_Price" FOREIGN KEY
(
Product_ID
)
REFERENCES Product
(
Product_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Promo_CD_Detail
ADD CONSTRAINT "Product-Promo_CD_Detail" FOREIGN KEY
(
Product_ID
)
REFERENCES Product
(
Product_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Product_Detail
ADD CONSTRAINT "Product-to-Product_Detail" FOREIGN KEY
(
Product_ID
)
REFERENCES Product
(
Product_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Promo_CD_Detail
ADD CONSTRAINT "Promo_CD-Promo_CD_Detail" FOREIGN KEY
(
Promo_ID
)
REFERENCES Promo_CD
(
Promo_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Order_Payment_Shipping_Method
ADD CONSTRAINT "Shipping_Rate-Order_Shipping" FOREIGN KEY
(
Shipping_Rate_ID
)
REFERENCES Shipping_Rate
(
Shipping_Rate_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Address_Book
ADD CONSTRAINT "State_CD-Address_Book" FOREIGN KEY
(
State_CD
)
REFERENCES State_CD
(
State_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Customer_Info
ADD CONSTRAINT "State_CD-Customer_Info" FOREIGN KEY
(
State_CD
)
REFERENCES State_CD
(
State_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Order_Shipping
ADD CONSTRAINT "State_CD-Order_Shipping" FOREIGN KEY
(
State_CD
)
REFERENCES State_CD
(
State_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Billing_Info
ADD CONSTRAINT "State_CD-To-Billing_Info" FOREIGN KEY
(
State_CD
)
REFERENCES State_CD
(
State_CD
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE iSetting
ADD CONSTRAINT "admin_user-iSetting" FOREIGN KEY
(
User_ID
)
REFERENCES Admin_User
(
User_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            53
-- CREATE INDEX                             0
-- ALTER TABLE                             81
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
